# Generated by Django 4.2 on 2023-06-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_about_alter_customuser_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='work_duties',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
