# Generated by Django 4.2 on 2023-06-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='life_status',
            field=models.CharField(choices=[('s', 'Single'), ('ir', 'In relationship')], default='s', max_length=2),
        ),
    ]
