# Generated by Django 4.2 on 2023-07-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contact_customuser_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
