# Generated by Django 4.2 on 2023-08-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_fol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fol',
        ),
    ]
