# Generated by Django 4.2 on 2023-07-12 15:33

from django.db import migrations, models
import posts.services


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_body_post_text_alter_post_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=posts.services.upload_video_path),
        ),
    ]
